/*************** AUTO GENERATED BY REMOTE CONTROL MODULE ***************/

var config = 
{
  address: '0.0.0.0',
  ipWhitelist: [],
  modules: [
    {
      module: 'alert',
      config: {}
    },
    {
      module: 'updatenotification',
      position: 'top_bar',
      config: {}
    },
    {
      module: 'clock',
      position: 'top_left',
      config: {}
    },
    {
      module: 'calendar',
      position: 'top_left',
      header: 'Holidays & Events',
      config: {
        calendars: [
          {
            symbol: 'holiday-calendar',
            url: 'https://www.calendarlabs.com/ical-calendar/ics/33/India_Holidays.ics'
          },
          {
            symbol: 'our-events',
            url: 'https://calendar.google.com/calendar/ical/smartaimirror1%40gmail.com/public/basic.ics'
          }
        ]
      }
    },
    {
      module: 'MMM-Remote-Control',
      position: 'bottom_left',
      config: {
        apiKey: 'b93a4457216940cd962f4e683e5d3886'
      }
    },
    {
      module: 'compliments',
      position: 'lower_third',
      header: '',
      config: {
        compliments: {
          anytime: [
            'Hello! From Team Smart AI Mirror :)'
          ],
          morning: [
            'Good Morning, Dear!',
            'Enjoy your Day!',
            'How was your sleep?',
            'You look Amazing for the Day!'
          ],
          afternoon: [
            'Hello, Handsome you look Amazing!',
            'Good Afternoon! Hope you are having a Joyful Day:)',
            'Smile😃 More with team Smart AI Mirror!',
            'Greetings from team Smart AI Mirror'
          ],
          evening: [
            'Wow, you look Great!',
            'You look Nice!',
            'The Dress Looks Awesome!',
            'Good Evening! I hope you had a nice and productive day'
          ],
          '....-01-01': [
            'Happy New Year!'
          ]
        }
      }
    },
    {
      module: 'weather',
      position: 'top_right',
      header: '',
      config: {
        location: 'Ahmedabad',
        locationID: '1279233',
        apiKey: 'd345dab86ab7e8a94b1c12062e18e273'
      }
    },
    {
      module: 'weather',
      position: 'top_right',
      header: 'Weather Forecast',
      config: {
        type: 'forecast',
        location: 'Ahmedabad',
        locationID: '1279233',
        apiKey: 'd345dab86ab7e8a94b1c12062e18e273'
      }
    },
    {
		module: 'MMM-Screencast',
		position: 'bottom_right', // This position is for a hidden <div /> and not the screencast window
		config: {
			position: 'bottomRight',
			height: 300,
			width: 500,
		}
    },
    {
      module: 'newsfeed',
      position: 'bottom_bar',
      config: {
        feeds: [
          {
            title: 'Ahmedabad Times',
            url: 'https://timesofindia.indiatimes.com/rssfeeds/-2128821153.cms'
          }
        ]
      }
    },
    {
      module: 'MMM-GoogleAssistant',
      position: 'bottom_left',
      header: '',
      config: {
        success: true,
        query: {
          data: 'defaultConfig',
          module: 'MMM-GoogleAssistant'
        },
        data: {
          header: 'Google Asistant',
          maxWidth: '100%',
          publishKey: 'PUBLISH_KEY',
          subscribeKey: 'SUBSCRIBE_KEY',
          updateDelay: 500
        }
      }
    }
  ],
  useHttps: false,
  httpsPrivateKey: '',
  httpsCertificate: '',
  locale: 'en-US'
}

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;}
